name: 同步到CNB
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 同步到CNB仓库
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/frappecn/docs.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.GIT_PASSWORD }} \
            -e PLUGIN_BRANCH="" \
            -e PLUGIN_GIT_USER="wolono" \
            -e PLUGIN_GIT_EMAIL="wolone@live.com" \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
